// Generated by CoffeeScript 1.6.2
(function() {
  var input, input_empty, messages, output, output_empty;

  messages = ["Nope", "Keep Trying", "Nadda", "Sorry", "No one's home", "Arg", "Bummer", "Faux pas", "Whoops", "Snafu", "Blunder"];

  input = $("input.test");

  input_empty = "*Enter a date (or time) here";

  output = $("p.test.output");

  output_empty = "Type a date above";

  input.val(input_empty);

  output.text(output_empty);

  input.keyup(function(e) {
    var date;

    output.removeClass();
    if (input.val().length > 0) {
      date = Date.parse(input.val());
      if (date !== null) {
        input.removeClass();
        return output.addClass("accept").text(date.toString("dddd, MMMM dd, yyyy h:mm:ss tt"));
      } else {
        input.addClass("validate_error");
        return output.addClass("error").text(messages[Math.round(messages.length * Math.random())] + "...");
      }
    } else {
      output.text = output_empty;
      return output.addClass("empty");
    }
  });

  input.focus(function(e) {
    if (input.val() === input_empty) {
      return input.val("");
    }
  });

  input.blur(function(e) {
    if (input.val() === "") {
      return input.val(input_empty).removeClass();
    }
  });

}).call(this);
